### PR TITLE
Initial encryption support

### LINKED ISSUE #31: optionally support encryption
Because databases might contain sensible data, we should support to encrypt the data before storing them.

This can all be done with the standard library, a good example with explanation with AES can be found here: https://levelup.gitconnected.com/a-short-guide-to-encryption-using-go-da97c928259f

### PR DESCRIPTION
**Pull request by majst01**
closes #31 

Adds encryption with aes from golang stdlib, only enabled if encryption key is given. Actually all 3 backup providers supported.

TODO: tests

### CODE REVIEW

**Comment by mwennrich** [comment]
Why not placing encryption generic in backup.go after compression, before uploading?

**Comment by majst01** [comment]
good point, wait a second

**Comment by majst01** [comment]
unsure if we should use a cli which is available on linux instead of our homegrown implementation. At least we should implement a possibility into this application to decrypt downloaded backups locally, for debugging and testing purpose.

WDYT ?

**Comment by mwennrich** [comment]
Maybe a "no database" mode, where the files get downloaded, decrypted, and decompressed?

**Comment by majst01** [comment]
Yes, added a `--download-only` flag to the `restore` command.

**Comment by majst01** [comment]
Another option would be to implement support for SSE-C, or SSE-S3 as described https://docs.aws.amazon.com/AmazonS3/latest/dev/ServerSideEncryptionCustomerKeys.html

Ceph RGW does support this as well: https://docs.ceph.com/en/latest/radosgw/encryption/#customer-provided-keys

**Comment by majst01** [comment]
implemented with #97

**Pull request closed without merging**
